### ISSUE TITLE
Display support

### ISSUE THREAD

**Issue by Cxarli** [cy384/fl2000_get_edid#1]
Hey :)

I love your project, and I'm amazed by what you've done. Is there any change you will be able to add support for displaying things on screen? I bought this thing, and after a lot of trouble with drivers for Windows, I also don't get it to work on Linux. I could test things if you would like me to.

**Comment by cy384** [comment]
Thanks for your interest.  With my current workload it's unlikely I'll have anything more written sooner than a few months.  I'll add another comment here when there's something you might find useful.
