### ISSUE TITLE
Display support

### ISSUE THREAD

**Issue by KeizerDev** [cy384/fl2000_get_edid#2]
I'm gathered to pay you like 50 dollar if you can fix this thing. I've bought like 2 of them and can't really get them to work at all with my 2 displays. I have 2 but just 1 hdmi port. Do you think you can manage to fix this?

**Comment by cy384** [comment]
I appreciate your interest.  Unfortunately, I am quite busy with academic pursuits at the moment.  Once I have time and get more work done on this, I'll let you know.

**Comment by Cxarli** [comment]
Just a quick note; for $50 you could buy a Linux-supporting HDMI adapter [like this one](https://www.amazon.co.uk/gp/product/B0038P1TP4/ref=as_li_tf_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=B0038P1TP4&linkCode=as2&tag=plugable-21) which is supported, according to [plugable](http://plugable.com/products/uga-2k-a).

That aside, I also bought this FL2000 product, so if you have time :pray:
